// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvoglvszrbmfqqytgkno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2b2dsdnN6cmJtZnFxeXRna25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDgxNjIsImV4cCI6MjA2MDkyNDE2Mn0.k2B7tyuc1K16mr6wRQ1XU_z1IP-9lhIOZTCF08FC0SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);